/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadingIndexRouteImport } from './routes/reading/index'
import { Route as ReadingArticleIdRouteImport } from './routes/reading/$articleId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingArticleIdRoute = ReadingArticleIdRouteImport.update({
  id: '/reading/$articleId',
  path: '/reading/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reading/$articleId': typeof ReadingArticleIdRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reading/$articleId': typeof ReadingArticleIdRoute
  '/reading': typeof ReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/reading/$articleId': typeof ReadingArticleIdRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/reading/$articleId' | '/reading/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/reading/$articleId' | '/reading'
  id: '__root__' | '/' | '/about' | '/reading/$articleId' | '/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReadingArticleIdRoute: typeof ReadingArticleIdRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$articleId': {
      id: '/reading/$articleId'
      path: '/reading/$articleId'
      fullPath: '/reading/$articleId'
      preLoaderRoute: typeof ReadingArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReadingArticleIdRoute: ReadingArticleIdRoute,
  ReadingIndexRoute: ReadingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
